### ISSUE TITLE
file not ASCII text

### ISSUE THREAD

**Issue by Jakob-SD** [blingenf/copydetect#23]
Hi there

When I run `copydetect -t <folder>` I get the error "file not ASCII text".

I have tried with a folder containing pdf files and a folder containing txt files, with same result.

Any clues on what I'm doing wrong?

**Comment by blingenf** [comment]
For PDF files this is expected, copydetect can only parse plain text files. With txt files it should work fine, though. Can you provide more information about what files you're processing and what the error output looks like?

**Comment by Jakob-SD** [comment]
Thank you for getting back to me. The error was purely mine, and I apologise for the inconvenience. 🙏

**Comment by dongmingli-Ben** [comment]
I met this exact problem when my files contain some unicode characters, such as Chinese characters. Is there any options that I can use for utf-8 files?

**Comment by blingenf** [comment]
@dongmingli-Ben UTF-8 encoded text works fine on my machine but it looks like the default encoding used by python is operating system specific, which may be causing your issue: https://peps.python.org/pep-0597/#using-the-default-encoding-is-a-common-mistake. 

Based on that PEP it seems the file loading code should be explicitly specifying UTF-8. But a command line option for controlling encoding may also be useful. I'll look into this later this week.

**Comment by dongmingli-Ben** [comment]
I look into the code and it appears that on my machine, utf-8 files cannot be opened and read successfully without the encoding option utf-8 in ```file.read```. Add ```encoding='utf-8'``` to detector.py [line 83] fixes the problem for me.

**Comment by blingenf** [comment]
@dongmingli-Ben Thank you for testing that. I just released `copydetect==0.4.3`, which includes the fix. Let me know if you still have encoding issues with the latest version.
