### ISSUE TITLE
Taking high memory for large set of files

### ISSUE THREAD

**Issue by ramsane** [blingenf/copydetect#28]
I was trying to test this for large code base like around 4000 files. Just to take the limits, I took 3 files and made 1500 copies each. I was through the source code. But it was taking around 7 GB. After some digging, I found out that it was majorly from the slice_matrix.

It was a nested list. I tried converting that to default dict (2D). But no luck. It was taking even more time with same 7GB memory.

Any ideas on how to reduce the memory footprint?

And for a such a large set of files, generating the HTML report doesn't make sense. With just the information like token overlap, similarities and sliced would be enough I feel.

**Comment by ramsane** [comment]
Any Ideas ??

**Comment by blingenf** [comment]
Thanks for the report!

The slice matrix is generally quite sparse and should definitely be a dictionary. Changing the data structure alone probably didn't help because the detection loop is currently storing empty slice entries for files with no similarity. I'll refactor this.

Depending on how much overlap there is in the file set, I think HTML report generation is probably taking up even more memory. I agree the HTML report isn't very helpful when there are a huge number of files --  I'll look into implementing some sort of plain text/raw data output option.

**Comment by ramsane** [comment]
Thanks.. Sorry for the late reply.. I was not even generating the report.. The memory is just for the comparison loop method.

**Comment by ramsane** [comment]
I was thinking that instead of providing just the report, it would be better if we give a CSV or something like that with just the paris, similarity and the slices for each pair.. This option would be great if anyone wants to use the results elsewhere.

**Comment by blingenf** [comment]
Getting rid of the unnecessary empty slices seems to have a pretty significant impact on memory usage. I think there's still some redundancy in this code I can clean up so I'll look into that before getting these changes in but my working branch is at `fix/slice_mtx_memory` if you'd like to check how it affects the memory usage you're seeing.

![memory_usage_fix](https://user-images.githubusercontent.com/22311737/213842948-632f78f3-5dbc-4833-be12-19c82a8a6481.png)

CSV output is a great idea, I'll look into that after I get the memory fix merged.

**Comment by ramsane** [comment]
I'll check for sure.. And the code is so well written and simple. If anyone wants they can definetly can take the pieces out and generate csv or whatever they wish to generate.. But having the feature is probably is the best idea.

And I also ran some tests.. Even If I write to disk for each comparision or for few comparisions, it is taking little longer. And  I was doing duplicate comparisions as I wasn't storing the results. We have to somehow reduce the comparisions and the memory. 😀. let's see if anything comes up..

**Comment by ramsane** [comment]
And one small thing.. I tried to put it to csv. But because we have some NumPy arrays (slices), JSON would be a better option.

**Comment by ramsane** [comment]
This is by assuming that we have some non-copied files (which is the most real world case). Because of that we have some empty slices. And in my case(4500 files), there are only 3 unique files(each of them are just minor modifications of the other). So,  I don't think this will help. But it's good that it improves the performance in some real world cases.

**Comment by ramsanegl** [comment]
We can close this one as the pr is already merged.

**Comment by blingenf** [comment]
Partially addressed by #31
