### ISSUE TITLE
detector.py only reads utf-8 encoded files

### ISSUE THREAD

**Issue by prof-danielc** [blingenf/copydetect#42]
copydetect was throwing "file not ASCII text" for multiple files I am working on. In detector.py it expects all readings to be in utf-8, so I used chardet to automagically detect file encodings and set the appropriate encoding when opening a file.

Fix 1.1 - add to imports:
import chardet

Fix 1.2 - detect character encoding:
In "CodeFingerPrint.__init__"

change:
"with open(file, encoding="utf-8") as code_fp:"

to:
rawdata = open(file, "rb").read()
encoding = chardet.detect(rawdata)['encoding']
with open(file, encoding=encoding) as code_fp:

This will allow copydetect to work with files of any encoding. I had this problem on my system and had to fix it.

**Comment by blingenf** [comment]
I've created a `fix/other_encodings` branch that allows encoding specification or autodetection if `chardet` is installed. I still have to do a bit of cleanup and documentation updating but if you install the package from that branch you should be able to use `--encoding DETECT` on the CLI to read the non-utf8 files.

**Comment by blingenf** [comment]
The CLI flag allowing other encodings (#43) has been included in copydetect 0.4.6
