### ISSUE TITLE
feat: include version-id and parameters in the report

### ISSUE THREAD

**Issue by ankostis** [blingenf/copydetect#45]
With significant changes in the scores from 0.4.2+, its important for the provenance of html report-files to contain the version of the program that generated the match ratios.
The cli-options used to generate the report are also useful when comparing results.

**Comment by blingenf** [comment]
I'll include this in the next release. Note however that it won't apply retroactively to previous releases, so only versions >0.4.6 will include the identifier.

**Comment by ankostis** [comment]
The cli-options used are also needed.
